### PR TITLE
add cloud scheduler notebook

### PR DESCRIPTION
**Pull request by deep-diver**
I was able to create Cloud Scheduler's job via `gcloud` command.
However, I failed on the other way about using `google-cloud-scheduler` SDK.

Please share any ideas to fix this issue. Especially, I don't really understand what `parent` parameter is in `create_job` method.

### CODE REVIEW

**Review by sayakpaul — CHANGES_REQUESTED** [review]
* Seems like you had already created the Cloud Function beforehand? If so, I think adding a note on how did you do would be helpful for the readers. I know we covered that in [this notebook](https://github.com/sayakpaul/CI-CD-for-Model-Training/blob/main/cloud_function_trigger.ipynb) but having that in the Scheduler notebook would make it more standalone. 
* Add substantial notes about any assumptions the notebook makes regarding the prerequisites. 
* Rectify the references and other headers. 
* It's okay to run it from a Cloud Notebook instance. In that case please remove the `Open in Colab` cell and the other irrelevant cells that are performing authentication. Instead, you can document what needs to be done for that purpose. 
* Might be a good idea to spell out what `--schedule "*/3 * * * *"` stands for i.e. what exactly is this schedule and where the readers can learn more about these schedules.

For the issue you are facing, does [this thread](https://stackoverflow.com/questions/60681672/how-to-create-a-job-with-google-cloud-scheduler-python-api) help?

**Comment by deep-diver** [comment]
@sayakpaul 

please take a look, I have addressed some of your comments.
I have run this notebook in GCP environment, but will add Colab button later on (the content itself contains Colab related things).

**Comment by sayakpaul** [comment]
Looks amazing. I can merge it now or do you have anything else to add to the notebook?

**Comment by deep-diver** [comment]
Pretty much done for now :)

**Review by sayakpaul — APPROVED** [review]

**Pull request merged**
